services:
  db:
    image: postgres:16-alpine
    container_name: wrapp_db_prod
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: wrapp_production
    volumes:
      - postgresql_data_prod:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d wrapp_production -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: wrapp_redis_prod
    restart: always
    command: redis-server
    volumes:
      - redis_data_prod:/data
    ports:
      - 6379:6379

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: wrapp_web_prod
    restart: always
    environment:
      RAILS_ENV: production
      TZ: Asia/Tokyo
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
      DATABASE_NAME: wrapp_production
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgresql_data_prod:
  redis_data_prod:
